# Generated by Django 6.0.2 on 2026-03-04 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealtorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.CharField(blank=True, help_text='URL or path to profile photo', max_length=500)),
                ('phone_number_1', models.CharField(blank=True, max_length=20)),
                ('phone_number_2', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('address_type', models.CharField(choices=[('actual', 'Actual Address'), ('po_box', 'PO Box')], default='actual', max_length=10)),
                ('business_website', models.URLField(blank=True)),
                ('license_states', models.CharField(blank=True, help_text='Comma separated state codes', max_length=255)),
                ('serving_states', models.CharField(blank=True, help_text='Comma separated state codes', max_length=255)),
                ('serving_cities', models.TextField(blank=True, help_text='Comma separated city names')),
                ('biography', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='realtor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Realtor Profile',
                'verbose_name_plural': 'Realtor Profiles',
            },
        ),
    ]
