# Generated by Django 6.0.2 on 2026-03-04 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lenderprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.CharField(blank=True, help_text='URL or path to profile photo', max_length=500)),
                ('phone_number_1', models.CharField(blank=True, max_length=20)),
                ('phone_number_2', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('address_type', models.CharField(choices=[('actual', 'Actual Address'), ('po_box', 'PO Box')], default='actual', max_length=10)),
                ('business_website', models.URLField(blank=True)),
                ('serving_states', models.CharField(blank=True, help_text='Comma separated state codes', max_length=255)),
                ('serving_cities', models.TextField(blank=True, help_text='Comma separated city names')),
                ('biography', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_number', models.CharField(blank=True, help_text='Broker license number', max_length=100)),
                ('license_states', models.CharField(blank=True, help_text='Comma separated state codes', max_length=255)),
                ('is_international', models.BooleanField(default=False)),
                ('is_nationwide', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='broker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broker Profile',
                'verbose_name_plural': 'Broker Profiles',
            },
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.CharField(blank=True, help_text='URL or path to profile photo', max_length=500)),
                ('phone_number_1', models.CharField(blank=True, max_length=20)),
                ('phone_number_2', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('address_type', models.CharField(choices=[('actual', 'Actual Address'), ('po_box', 'PO Box')], default='actual', max_length=10)),
                ('business_website', models.URLField(blank=True)),
                ('serving_states', models.CharField(blank=True, help_text='Comma separated state codes', max_length=255)),
                ('serving_cities', models.TextField(blank=True, help_text='Comma separated city names')),
                ('biography', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license_state', models.CharField(blank=True, help_text='2-letter state code', max_length=10)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('business_card_front', models.CharField(blank=True, help_text='URL or path to front of business card', max_length=500)),
                ('business_card_back', models.CharField(blank=True, help_text='URL or path to back of business card', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Profile',
                'verbose_name_plural': 'Partner Profiles',
            },
        ),
        migrations.CreateModel(
            name='PromoterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.CharField(blank=True, help_text='URL or path to profile photo', max_length=500)),
                ('phone_number_1', models.CharField(blank=True, max_length=20)),
                ('phone_number_2', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('company_address', models.TextField(blank=True)),
                ('address_type', models.CharField(choices=[('actual', 'Actual Address'), ('po_box', 'PO Box')], default='actual', max_length=10)),
                ('business_website', models.URLField(blank=True)),
                ('serving_states', models.CharField(blank=True, help_text='Comma separated state codes', max_length=255)),
                ('serving_cities', models.TextField(blank=True, help_text='Comma separated city names')),
                ('biography', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_type', models.CharField(blank=True, choices=[('photography', 'Photography'), ('marketing_agency', 'Marketing Agency'), ('social_media', 'Social Media Management'), ('videography', 'Videography'), ('staging', 'Staging Services'), ('virtual_tour', 'Virtual Tour Provider'), ('other', 'Other')], max_length=50)),
                ('business_card_front', models.CharField(blank=True, help_text='URL or path to front of business card', max_length=500)),
                ('business_card_back', models.CharField(blank=True, help_text='URL or path to back of business card', max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promoter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promoter Profile',
                'verbose_name_plural': 'Promoter Profiles',
            },
        ),
    ]
