# Generated by Django 6.0.2 on 2026-03-09 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_brokerprofile_partnerprofile_promoterprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.CharField(db_index=True, max_length=6, unique=True)),
                ('property_type', models.CharField(choices=[('single_family', 'Single Family'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('multi_family', 'Multi Family'), ('land', 'Land'), ('commercial', 'Commercial')], default='single_family', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('sold', 'Sold'), ('off_market', 'Off Market')], default='active', max_length=20)),
                ('street_address', models.CharField(max_length=255)),
                ('unit_apt', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('bedrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('lot_size', models.CharField(blank=True, max_length=50)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('floor_type', models.CharField(blank=True, max_length=100)),
                ('kitchen_type', models.CharField(blank=True, max_length=100)),
                ('foundation_type', models.CharField(blank=True, max_length=100)),
                ('exterior', models.CharField(blank=True, max_length=100)),
                ('roof', models.CharField(blank=True, max_length=100)),
                ('appliances', models.TextField(blank=True, help_text='Comma separated list')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.CharField(max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.property')),
            ],
            options={
                'verbose_name': 'Property Photo',
                'verbose_name_plural': 'Property Photos',
                'ordering': ['order'],
            },
        ),
    ]
