# Generated by Django 6.0.2 on 2026-03-09 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notificationsettings_openhouse_perk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LenderProductCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('card_image', models.CharField(help_text='URL or path to lending product card image', max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lender Product Card',
                'verbose_name_plural': 'Lender Product Cards',
                'ordering': ['order'],
            },
        ),
    ]
