# Generated by Django 6.0.1 on 2026-03-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lenderproductcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerprofile',
            name='business_card_back',
            field=models.CharField(blank=True, help_text='URL or path to back of business card', max_length=500),
        ),
        migrations.AddField(
            model_name='brokerprofile',
            name='business_card_front',
            field=models.CharField(blank=True, help_text='URL or path to front of business card', max_length=500),
        ),
        migrations.DeleteModel(
            name='LenderProductCard',
        ),
    ]
