# Generated by Django 6.0.1 on 2026-03-10 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_realtorprofile_business_card_back_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brokerprofile',
            name='business_card_back',
        ),
        migrations.RemoveField(
            model_name='brokerprofile',
            name='business_card_front',
        ),
        migrations.RemoveField(
            model_name='realtorprofile',
            name='business_card_back',
        ),
        migrations.RemoveField(
            model_name='realtorprofile',
            name='business_card_front',
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('realtor_name', models.CharField(max_length=255)),
                ('realtor_email', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('discount_value', models.CharField(max_length=100)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('property_link', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Promo Code',
                'verbose_name_plural': 'Promo Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
