# Generated by Django 6.0.1 on 2026-03-10 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_brokerprofile_business_card_back_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('title_company', 'Title Company'), ('home_inspector', 'Home Inspector'), ('appraiser', 'Appraiser'), ('handyman', 'Handyman'), ('contractor', 'Contractor'), ('insurance', 'Insurance Agent'), ('moving', 'Moving Company'), ('cleaning', 'Cleaning Service'), ('landscaping', 'Landscaping'), ('other', 'Other')], max_length=50)),
                ('service_area', models.CharField(blank=True, help_text='Description of service area', max_length=255)),
                ('serving_states', models.CharField(blank=True, help_text='Comma separated state codes', max_length=255)),
                ('serving_cities', models.TextField(blank=True, help_text='Comma separated city names')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.partnerprofile')),
            ],
            options={
                'verbose_name': 'Partner Service',
                'verbose_name_plural': 'Partner Services',
                'ordering': ['-created_at'],
            },
        ),
    ]
